### ISSUE TITLE
Not opening Big Sur - Mac

### ISSUE THREAD

**Issue by MarkJThomas** [olivierfriard/DORIS#11]
Hi Oliver,
I hope you are well. I downloaded and opened the latest version of Doris on my mac but the application doesn't open. Just says application not responding, are you able to provide guidance please?
Also, does the app work just for closed environments or can open environments work as well?
Much appreciated the time and effort you put into making these apps.
TIA,
Mark

**Comment by TomDickins** [comment]
Hello: Did you find a solution to this problem? I am having the same issue with my Mac using Ventura 13.0 OS.

**Comment by olivierfriard** [comment]
Hi,
a colleague noticed the same problem.
My advice is to install DORIS into a Python virtual environment.
You can find the procedure under the Linux install section of the documentation:
https://doris.readthedocs.io/en/latest/#gnu-linux

Best regards

Olivier
