### ISSUE TITLE
DORIS stalls at opening on Mac

### ISSUE THREAD

**Issue by TomDickins** [olivierfriard/DORIS#12]
Hello - I have mounted the latest .dmg on my Mac (OS Ventura 13.0) and each time I open DORIS it simply bounces for a couple of minutes, asks me to give permissions via Privacy and Security, which I do, then I click open and it bounces for a long time with spinning colour wheel then crashes out. I do not have this problem on my Mac in the lab, running Monterey. Any help gratefully received.

**Comment by olivierfriard** [comment]
Hi,
a colleague noticed the same problem.
My advice is to install DORIS into a Python virtual environment.
You can find the procedure under the Linux install section of the documentation:
https://doris.readthedocs.io/en/latest/#gnu-linux

Best regards

Olivier

**Comment by TomDickins** [comment]
Sorry for the very slow response - but many thanks for this. It is appreciated.

Tom
