### ISSUE TITLE
Doris will not open after double clicking the icon on Mac

### ISSUE THREAD

**Issue by bparrington7** [olivierfriard/DORIS#7]
Hello,

I am having trouble opening Doris! I downloaded all of the necessary files from the most recent update (06-13-20) and followed the instructions on how to open Doris (for Mac, it is installing it and opening it by double-clicking on the icon). However, after double-clicking on the icon, Doris tries to open but it never does after 3-4 tries so far.

I thought it was a security issue (since I know Mac OS Catalina 10.15 has issues with running/opening downloads/software not verified by Apple), but I have checked my Security and Privacy settings to see if Doris needed to ask my permission. It did, so I enabled Doris in the Security and Privacy settings.

Also, as I double-click the icon and the icon "jumps" to show that it is in the process of opening the program and stops as soon as the program is opened. However, the Doris icon "jumps" for about 1 minute and then stops, but does not actually open the program.

Therefore, I was wondering if there were any other tips to get Doris to open properly? Thanks!

-Brianna

**Comment by TomDickins** [comment]
Hello: Did you find a solution to this problem? I am having the same issue with my Mac using Ventura 13.0 OS.

**Comment by olivierfriard** [comment]
Hi,
My advice is to install DORIS into a Python virtual environment.
You can find the procedure under the Linux install section of the documentation:
https://doris.readthedocs.io/en/latest/#gnu-linux

Best regards

Olivier
